//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchStrs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchStrs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Res.SearchStrs", typeof(SearchStrs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}.
        /// </summary>
        public static string regex_IP {
            get {
                return ResourceManager.GetString("regex_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;|&quot;| )(http://|https://)?([a-z0-9\-]+\.)+(com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw| [rest of string was truncated]&quot;;.
        /// </summary>
        public static string regex_URL {
            get {
                return ResourceManager.GetString("regex_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (([0-9])+\.)+.
        /// </summary>
        public static string regex_Version {
            get {
                return ResourceManager.GetString("regex_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class, &apos;F9iKBc&apos;)].
        /// </summary>
        public static string xPath_Downloads {
            get {
                return ResourceManager.GetString("xPath_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[contains(@class, &apos;rBxtY&apos;)].
        /// </summary>
        public static string xPath_icon {
            get {
                return ResourceManager.GetString("xPath_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[contains(@class, &apos;ZbWJPd uBIrad&apos;)].
        /// </summary>
        public static string xPath_LastUpdate {
            get {
                return ResourceManager.GetString("xPath_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h1[contains(@class, &apos;Pa2dE&apos;)].
        /// </summary>
        public static string xPath_Name {
            get {
                return ResourceManager.GetString("xPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class, &apos;cJI8ee&apos;)].
        /// </summary>
        public static string xPath_Provider {
            get {
                return ResourceManager.GetString("xPath_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class, &apos;Vq0ZA&apos;)].
        /// </summary>
        public static string xPath_Rating {
            get {
                return ResourceManager.GetString("xPath_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //p[contains(@class, &apos;xJEoWe&apos;)].
        /// </summary>
        public static string xPath_Reviews {
            get {
                return ResourceManager.GetString("xPath_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class, &apos;N3EXSc&apos;)].
        /// </summary>
        public static string xPath_Version {
            get {
                return ResourceManager.GetString("xPath_Version", resourceCulture);
            }
        }
    }
}
